import os

GRIDGRAPH, NETGEN, GRIDGEN, GOTO = 0, 1, 2, 3
GENERATOR_NAMES = ["GRIDGRAPH", "NETGEN", "GRIDGEN", "GOTO"]
NUM_GENERATORS = 4
TARGET_INSTANCES = [15000, 15000, 15000, 15000]

NUM_ALGORITHMS = 4
TIME_LIMIT = 10 * 10 ** 6
MAX_SAMPLES = 20000

PATH_TO_PROJECT = os.path.join("../..")
PATH_TO_DATA = os.path.join(PATH_TO_PROJECT, "data", "generated_data")
